### ISSUE TITLE
Compile - Parse markdown file

### ISSUE THREAD

**Issue by nicrausaz** [dil-classroom/projet-akoumba_crausaz_scharwath#27]
### Time prevision
| Optimistic | Pessimistic | Expected | Real    |
|------------|-------------|----------|---------|
| 2 hours    | 4 hours     | 2 hours  | 2 hours |

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

On command `build /mon/site`, read .md files and parse them:

- First part contains the YAML data, this needs to be stored and used to generete static pages
- Second part contains markdown, this will be the content of our static page

**Describe alternatives you've considered**
-  

**Additional context**
-

**Comment by maxscharwath** [comment]
Need the build command, to compile all files in src to build folder
