### ISSUE TITLE
Refactor of sprint 1

### ISSUE THREAD

**Issue by nicrausaz** [dil-classroom/projet-akoumba_crausaz_scharwath#45]
### Time prevision
| Optimistic | Pessimistic | Expected | Real    |
|------------|-------------|----------|---------|
| 2 hours    | 5 hours     | 3 hours  | x hours |

**Is your feature request related to a problem? Please describe.**
We need to refactor the code of the sprint 1 so we can start the sprint 2 on a clean codebase.

**Comment by maxscharwath** [comment]
We had a problem, bits of the code of this PR disappeared during some merges.
