### ISSUE TITLE
Add system tests

### ISSUE THREAD

**Issue by nicrausaz** [dil-classroom/projet-akoumba_crausaz_scharwath#50]
### Time prevision
| Optimistic | Pessimistic | Expected | Real    |
|------------|-------------|----------|---------|
| 1 hours    | 3 hours     | 2 hours  | x hours |

**Is your feature request related to a problem? Please describe.**
Implement some system tests

**Comment by maxscharwath** [comment]
Add a test to verify if the server works: check requests
