### ISSUE TITLE
Implement an abstraction of FileWatcher

### ISSUE THREAD

**Issue by nicrausaz** [dil-classroom/projet-akoumba_crausaz_scharwath#75]
### Time prevision
| Optimistic | Pessimistic | Expected | Real    |
|------------|-------------|----------|---------------------|
| 3 hours    | 5 hours     | 4 hours  | 4 hours |

**Is your feature request related to a problem? Please describe.**
Create an simple abstraction for watching files in a folder

**Describe the solution you'd like**
A modelisation is necessary

**Comment by maxscharwath** [comment]
The goal of our FileWatcher is to have a class who hide all muddy stuff like horrible while(true):
The goal is to have only one constructor with root path and an EventHandler who need to be implemented to catch files event. We can add a system to put files in ignore list: For example build dir
