### ISSUE TITLE
Integrate our filewatcher abstraction into build & serve commands

### ISSUE THREAD

**Issue by nicrausaz** [dil-classroom/projet-akoumba_crausaz_scharwath#76]
### Time prevision
| Optimistic | Pessimistic | Expected | Real    |
|------------|-------------|----------|---------|
| 3 hours    | 5 hours     | 4 hours  | 1 hours |

**Is your feature request related to a problem? Please describe.**
Add a --watch option to build & server command, that rebuild the files on the fly.

**Comment by maxscharwath** [comment]
I finally dont add -w to serve. I propose instead to run serve and build -w, because it's not the job of serve to build files.
