### ISSUE TITLE
Modelisation

### ISSUE THREAD

**Issue by nicrausaz** [dil-classroom/projet-akoumba_crausaz_scharwath#82]
### Time prevision
| Optimistic | Pessimistic | Expected | Real    |
|------------|-------------|----------|---------|
| 3 hours    | 6 hours     | 5 hours  | 2 hours |

**Is your feature request related to a problem? Please describe.**
We need to modelise & the filewatcher abstraction our codebase before making a refactor 

**Describe the solution you'd like**
UML Class diagramm & use case

**Comment by maxscharwath** [comment]
![FilesWatcher](https://user-images.githubusercontent.com/6887819/169915509-abf5cf50-d90c-4fe4-8d16-00fb8623a1e4.png)

Here is an example of what we want to implements.
